### PR TITLE
yo

### PR DESCRIPTION
**Pull request by L0ry-git**
yo

### CODE REVIEW

**Comment by SpeckyYT** [comment]
Remove the constant pls

**Comment by L0ry-git** [comment]
Allocate some memory for your social life before, ZI.

**Comment by SpeckyYT** [comment]
PR closed cause of: Triggered

**Comment by L0ry-git** [comment]
Imagine closing something else other than pull requests...

**Comment by SpeckyYT** [comment]
Imagine closing the closet :hoesmad:

**Comment by L0ry-git** [comment]
You're closely approaching c-loser! Man, my clause was close to awesomeness like never before!

**Pull request closed without merging**
